### ISSUE TITLE
Fails to clone riscv-qemu

### ISSUE THREAD

**Issue by abdullahyildiz** [esperantotech/boom-template#14]
It fails while initializing submodules.

**Comment by pentin-as** [comment]
What commands do you call?
What diagnostics?

**Comment by abdullahyildiz** [comment]
Commands:
```
git clone https://github.com/ccelio/boom-template.git
cd boom-template
./scripts/init-submodules.sh
```

Diagnostics:
> Cloning into 'riscv-qemu'...
> fatal: unable to connect to github.com:
> github.com[0: 192.30.253.112]: errno=Connection timed out
> github.com[1: 192.30.253.113]: errno=Connection timed out
> 
> Clone of 'git://github.com/riscv/riscv-qemu.git' into submodule path 'riscv-qemu' failed

**Comment by pentin-as** [comment]
1. This problem does not apply to Boom and to this repository. You do not clone a project with github.com. It is better to look for a solution on the Internet.
2. Try:
git config --global url.https://github.com/.insteadOf git://github.com/
