### ISSUE TITLE
Build fails due to Chisel3

### ISSUE THREAD

**Issue by tampler** [esperantotech/boom-template#15]
Hello
I followed installation instructions and tried to build a Small config with: 
make run CONFIG=SmallBoomConfig. I use Ubuntu 16.04, javac 1.8.0_181 and the latest rocket-chip

[info] Compiling 242 Scala sources to /home/bku/work/cores/bar/boom-template/rocket-chip/target/scala-2.12/classes ...
[error] /home/bku/work/cores/bar/boom-template/rocket-chip/src/main/scala/jtag/JtagStateMachine.scala:88:22: exception during macro expansion: 
[error] java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.tl$1()Lscala/collection/immutable/List;
[error] 	at chisel3.util.switch$$anonfun$2$$anon$2.unapply(Conditional.scala:100)
[error] 	at chisel3.util.switch$$anonfun$2.apply(Conditional.scala:100)
[error] 	at chisel3.util.switch$$anonfun$2.apply(Conditional.scala:97)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:86)
[error] 	at chisel3.util.switch$.impl(Conditional.scala:97)
[error]   switch (currState) {
[error]                      ^
[error] /home/bku/work/cores/bar/boom-template/rocket-chip/src/main/scala/rocket/PTW.scala:242:18: exception during macro expansion: 
[error] java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.tl$1()Lscala/collection/immutable/List;
[error] 	at chisel3.util.switch$$anonfun$2$$anon$2.unapply(Conditional.scala:100)
[error] 	at chisel3.util.switch$$anonfun$2.apply(Conditional.scala:100)
[error] 	at chisel3.util.switch$$anonfun$2.apply(Conditional.scala:97)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:86)
[error] 	at chisel3.util.switch$.impl(Conditional.scala:97)
[error]   switch (state) {

**Comment by jerryz123** [comment]
You should use the version of rocket-chip submoduled in boom-template, not the latest upstream rocket-chip.

**Comment by tampler** [comment]
Thanks
